update_fastlane

default_platform(:ios)

platform :ios do
  lane :sort_files do
    sh("perl ../sortXcodeProject.pl ../Meme.xcodeproj/project.pbxproj")
    sh("perl ../sortXcodeProject.pl ../WebAPI/WebAPI.xcodeproj/project.pbxproj")
    sh("perl ../sortXcodeProject.pl ../MemeData/MemeData.xcodeproj/project.pbxproj")
    # because the sort file script will cause some swift packages missing, so resolve packages after sorting
    # sh("xcodebuild -workspace ../Meme.xcworkspace -scheme Meme -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' build")
  end
end
