update_fastlane

default_platform(:ios)

platform :ios do

desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    
    build_app(scheme: "Meme")
   
    upload_to_testflight
   
    commit_version_bump(message: "Bump build number")
   
    push_to_git_remote
  end
end
