name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  XCODE_DESTINATION: 'platform=iOS Simulator,name=iPhone 16,OS=latest'
  DEVELOPER_DIR: /Applications/Xcode-16.0.0.app/Contents/Developer

jobs:
  build_and_test_meme:
    runs-on: self-hosted
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Info.plist
        run: |
          cd Meme/Resources
          plutil -replace GADApplicationIdentifier -string "ca-app-pub-3940256099942544~1458002511" Info.plist

      - name: Create GoogleService-Info-CI.plist
        run: |
          mkdir -p Meme/Resources
          echo "${{ secrets.GOOGLE_SERVICE_INFO_CI_PLIST }}" > Meme/Resources/GoogleService-Info-CI.plist

      - name: Clear Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Reset Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Install dependencies
        run: xcodebuild -resolvePackageDependencies -project Meme.xcodeproj

      - name: Xcode clean Meme project
        run: xcodebuild clean -project Meme.xcodeproj -scheme Meme -destination "${{ env.XCODE_DESTINATION }}"

      - name: Build Meme project
        run: xcodebuild build -project Meme.xcodeproj -scheme Meme -destination "${{ env.XCODE_DESTINATION }}"

      - name: Xcode clean MemeCI project
        run: xcodebuild clean -project Meme.xcodeproj -scheme MemeCI -destination "${{ env.XCODE_DESTINATION }}"

      - name: Run MemeCI tests
        run: xcodebuild test -project Meme.xcodeproj -scheme MemeCI -destination "${{ env.XCODE_DESTINATION }}"