name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  XCODE_DESTINATION: 'platform=iOS Simulator,name=iPhone 16,OS=latest'
  DEVELOPER_DIR: /Applications/Xcode-16.0.0.app/Contents/Developer

jobs:
  test_meme:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Reset Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Xcode Clean
        run: |
          xcodebuild clean -project Meme.xcodeproj -scheme Meme -destination "${{ env.XCODE_DESTINATION }}"

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project Meme.xcodeproj

      - name: Create plist file with sensitive data
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > Meme/APIConfig.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> Meme/APIConfig.plist
          echo '<plist version="1.0">' >> Meme/APIConfig.plist
          echo '<dict>' >> Meme/APIConfig.plist
          echo '  <key>API_KEY</key>' >> Meme/APIConfig.plist
          echo '  <string>testAPIKey</string>' >> Meme/APIConfig.plist
          echo '</dict>' >> Meme/APIConfig.plist
          echo '</plist>' >> Meme/APIConfig.plist

      - name: Run Meme tests
        run: |
          xcodebuild test -project Meme.xcodeproj -scheme Meme -destination "${{ env.XCODE_DESTINATION }}"
