name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd Meme
          xcodebuild -resolvePackageDependencies

      - name: Run tests
        run: |
          cd Meme
          xcodebuild test -scheme Meme -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
          xcodebuild test -scheme WebAPI -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
